### ISSUE TITLE
Call Recording

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [rubaiet/OpenVBX-Plugin-Combined-Call-Transfer-beta#1]
Hi, this plugin is very helpful... I see that you developed a call recording functionality for it... is it all possible to enable the call recording for outbound calls?

Thanks

**Comment by rubaiet** [comment]
Hi Daniel, this call transfer plugin do not deal with outbound calls.
But right now I am working for a new custom call record plugin for regular inbound (with DIAL applet) and outbound calls.

Best,
Rubai

**Comment by DanielFerreiraJorge** [comment]
Hi Rubai, thank you for your answer.

This is great news. Do you have an idea of when this plugin will be ready? I have a real need for something like this... and since you are already developing this, I can "sponsor" your development if this can help you to release this plugin as soon as possible... 

My exact needs are this:
1. Record Inbound and outbound calls
2. Transfer the call, from the dialpad... something like selecting a user name and transfer...

Are you interested? If yes, how long you think you can accomplish that?

Thanks!

**Comment by GChester** [comment]
I too have been watching this project.  We do quite a bit of custom work in OpenVBX

**Comment by DanielFerreiraJorge** [comment]
Ok, GChester, how long will it take to develop what I need?

**Comment by rubaiet** [comment]
I will try to finish recording for outbound calls within couple of days.
But transfer outbound call using dial pad needs some RND. 
I will keep you posted.

**Comment by DanielFerreiraJorge** [comment]
That is great rubaiet!

When I say ẗhat I need to transfer from the dialpad, it does not need to be from the dialpad... What I really want is to eliminate the necessity of using conferencing. I want to click in a user name and transfer the call... can be a php page... can be dialing a number in the dialpad (for instance.. each of my users have a distinct number... if I dial #number, it will send the call to another user...)... It can be anything really... I just need a easy way to transfer the call to another user...

Do you think this is possible?
Thanks!

**Comment by rubaiet** [comment]
Hello Daniel,
Sorry was forget due to workload.
I did developed another call-transfer-recording functionalities for OpenVBX and it worked on both inbound and outbound calls.  Right now we are distributing for commercial purpose only.

Thanks
